name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # 公式の「${UPLOAD_LOCATION}:/data」を long syntax + bind に変更
      - type: bind
        source: ${UPLOAD_LOCATION}   # 例: /data/immich/library
        target: /data
        is_directory: true
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      # 公式は named volume: model-cache:/cache のまま（最小修正のため保持）
      # → キャッシュも bind したければ以下に変更:
      # - type: bind
      #   source: /data/immich/cache
      #   target: /cache
      - model-cache:/cache
    env_file:
      - .env
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      # DB_STORAGE_TYPE: 'HDD'   # Uncomment if your DB disk is HDD
    volumes:
      # 公式の「${DB_DATA_LOCATION}:/var/lib/postgresql/data」を long syntax + bind に変更
      - type: bind
        source: ${DB_DATA_LOCATION}         # 例: /data/immich/postgres
        target: /var/lib/postgresql/data
        is_directory: true
    shm_size: 128mb
    restart: always

volumes:
  model-cache:
